package collections

fun main() {
    val count = mapOf(1 to "One", 2 to "Two", 3 to "Three")
    println("Count: $count")
    val countMore = mapOf<Int, String>()
    println("Count more: $countMore")
    println("Count on second key: ${count[2]}")
    println("Count on third key: ${count.get(3)}")
    println("Count map keys: ${count.keys}")
    println("Count map values: ${count.values}")
    val hashCount = hashMapOf(1 to "One", 2 to "Two", 3 to "Three")
    println("Hash count: $hashCount")
    println("Mapping 4")
    hashCount.put(4, "Four")
    println("Hash count after adding 4: $hashCount")
    println("Mapping 5")
    hashCount[5] = "Five"
    println("Hash count after adding 5: $hashCount")
    val hashCountMore = hashMapOf(7 to "Seven", 6 to "Six")
    println("Hash count more: $hashCountMore")
    hashCount.putAll(hashCountMore)
    println("Hash count after adding all the other hash count more: $hashCount")
    hashCount.remove(6)
    println("Hash count after removing 6: $hashCount")
    hashCount.replace(5, "Five", "FIVE")
    println("Hash count after replacing 5 with FIVE: $hashCount")
    hashCountMore.clear()
    println("Hash count more after clearing: $hashCountMore")
}