package collections

fun main() {
    val count = mapOf(1 to "One", 2 to "Two", 3 to "Three")
    println("Count: $count")
    val countMore = mapOf<Int, String>()
    println("Count more: $countMore")
    println("Count on second key: ${count[2]}")
    println("Count on third key: ${count.get(3)}")
    println("Count map keys: ${count.keys}")
    println("Count map values: ${count.values}")
    val hashCount = hashMapOf(1 to "One", 2 to "Two", 3 to "Three")
    println("Hash count: $hashCount")
    println("Mapping 4")
    hashCount.put(4, "Four")
    println("Hash count after adding 4: $hashCount")
    println("Mapping 5")
    hashCount[5] = "Five"
    println("Hash count after adding 5: $hashCount")
    val hashCountMore = hashMapOf(7 to "Seven", 6 to "Six")
    println("Hash count more: $hashCountMore")
    hashCount.putAll(hashCountMore)
    println("Hash count after adding all the other hash count more: $hashCount")
    hashCount.remove(6)
    println("Hash count after removing 6: $hashCount")
    hashCount.replace(5, "Five", "FIVE")
    println("Hash count after replacing 5 with FIVE: $hashCount")
    hashCountMore.clear()
    println("Hash count more after clearing: $hashCountMore")
    println("Is hash count empty? ${hashCount.isEmpty()}")
    println("Is hash count more empty? ${hashCountMore.isEmpty()}")
    println("Is hash count not empty? ${hashCount.isNotEmpty()}")
    println("Hash count size: ${hashCount.size}")
    println("Hash count contains key 3? ${hashCount.containsKey(3)}")
    println("Hash count contains value \"FIVE\"? ${hashCount.containsValue("FIVE")}")
    println("Hash count contains value \"Six\"? ${hashCount.containsValue("Six")}")
    println("Hash count contains key 6? ${hashCount.containsKey(6)}")

    val attendance = hashMapOf("Sept 23rd" to 2837, "Sept 24th" to 2938, "Oct 25th" to 4985, "Oct 26th" to 5002)
    println("Attendance to the Amusement Park: $attendance")
    println("Including attendance on Sept 26th")
    attendance["Sept 26th"] = 5001
    println("Attendance to the Amusement Park after adding Sept 26th: $attendance")
    println("How many people visited the park on Sept 23rd and 24th? ${attendance["Sept 23rd"]?.plus(attendance["Sept 24th"] ?: 0)}")
    println("Is data for Sept 22nd available? ${attendance.containsKey("Sept 22nd")}")
}